### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mebanks** [nutelabezgmo222/GRC_BE#1]
Hi, wanted to know if i can use this commercially? Do you want to collaborate?

**Comment by MaksymSolodovnykov** [comment]
Hello i appreciate your interest in my project. This project was built as my bachelor project and its quite raw for now  i have some plans to continue it as my master degree project. It requires a lot of additional coding before you can use in commercial purpose. What kind of collaboration do you offer?

**Comment by nutelabezgmo222** [comment]
Hello i appreciate your interest in my project. This project was built as my bachelor project and its quite raw for now i have some plans to continue it as my master degree project. It requires a lot of additional coding before you can use it in commercial purpose. What kind of collaboration do you offer?

**Comment by mebanks** [comment]
Hi,

Thanks for your feedback.
We provide solutions to multiple businesses and one of them is currently
searching for a GRC tool which is why we reached out to you. By
collaborating, we would have sold your solution and discuss a licence fee
to you for using it.

Best Regards,
Mario Ebanks

Mobile: +31 619809789
+95 92 636 90876

**Comment by nutelabezgmo222** [comment]
It sounds totally fine for me.
As i said there are a lot of features that should be implemented to meet business requirements.

**I dont mind if you take this project in current version for your purposes.**

Also i dont mind to help you. If you need something from me just let me know.
There you can see small presentation. Unfortunately it`s not translated to English but you can find some schemas and screenshots that you may be interested in.
[presentation.pptx](https://github.com/nutelabezgmo222/GRC_BE/files/14360168/presentation.pptx)

So if you need something from me you can reach me in telegram https://t.me/nutelabezgmo or gmail: solodovnikov.maksim123@gmail.com.

Best Regards,
Maksym Solodovnykov

**Comment by mebanks** [comment]
Thanks Maksim!
I will ask the team to take a look and if they decide to use it then we
will also inform you and work out a fee.
In the future, if you have any interesting projects, feel free to let me
know and we will check if we can use it for any of our clients.

Best Regards,
Mario Ebanks

Mobile: +31 619809789
+95 92 636 90876
